### ISSUE TITLE
Cannot convert Vars to array

### ISSUE THREAD

**Issue by mbrodala** [m1/Vars#12]
Currently there is no way to convert `Vars` instances into plain arrays which should be added to support more usescases.

An example is amending an app's configuration (plain array) with additional configuration loaded from files. Currently this is impossible.

**Comment by m1** [comment]
You can do `$vars->getContent()` to get a plain array back

**Comment by mbrodala** [comment]
OK, that was easier than expected. ;-)

I assume that this way the configuration source type (PHP, YAML, ...) doesn't matter, correct?

**Comment by m1** [comment]
Yes, by the time you call `getContent()` the source configs will of already be parsed.

**Comment by mbrodala** [comment]
Alright, thanks a lot. :-)

**Comment by m1** [comment]
You can also `getContent()` on individual imported files/fileresources, e.g. 

```
$vars->getResource('example.yml')->getContent();
```
