### ISSUE TITLE
I cannot login in my github desktop 

### ISSUE THREAD

**Issue by MarianaHCL** [m1/Vars#23]
github desktop (ibm) does not recognize my w3 credentials. I can login into w3 or https://github.ibm.com/HCL-PnP/ClearQuest901 with my w3 credentials but not on my GitHub desktop. i reinstalled GitHub deskktop and nothing changed.  
![image](https://user-images.githubusercontent.com/41688392/53025854-c5506b80-342f-11e9-99df-75b1a459e316.png)

**Comment by MarianaHCL** [comment]
on a browser, I can login but not on my desktop. On a browser it says it now uses SAML - i do not have a clue what's the password used for SAML by ibm gitbub browser. the question is why it does not let me login/or asking for credentials for my desktop github - see above screen capture.

**Comment by m1** [comment]
I think you've got the wrong repo.

**Comment by MarianaHCL** [comment]
what do you mean by wrong repo
